// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: mpc.v1.proto

package mpcv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionStatus int32

const (
	SessionStatus_SESSION_STATUS_UNSPECIFIED SessionStatus = 0
	SessionStatus_SESSION_STATUS_RUNNING     SessionStatus = 1
	SessionStatus_SESSION_STATUS_COMPLETED   SessionStatus = 2
	SessionStatus_SESSION_STATUS_FAILED      SessionStatus = 3
	SessionStatus_SESSION_STATUS_TIMED_OUT   SessionStatus = 4
)

// Enum value maps for SessionStatus.
var (
	SessionStatus_name = map[int32]string{
		0: "SESSION_STATUS_UNSPECIFIED",
		1: "SESSION_STATUS_RUNNING",
		2: "SESSION_STATUS_COMPLETED",
		3: "SESSION_STATUS_FAILED",
		4: "SESSION_STATUS_TIMED_OUT",
	}
	SessionStatus_value = map[string]int32{
		"SESSION_STATUS_UNSPECIFIED": 0,
		"SESSION_STATUS_RUNNING":     1,
		"SESSION_STATUS_COMPLETED":   2,
		"SESSION_STATUS_FAILED":      3,
		"SESSION_STATUS_TIMED_OUT":   4,
	}
)

func (x SessionStatus) Enum() *SessionStatus {
	p := new(SessionStatus)
	*p = x
	return p
}

func (x SessionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_mpc_v1_proto_enumTypes[0].Descriptor()
}

func (SessionStatus) Type() protoreflect.EnumType {
	return &file_mpc_v1_proto_enumTypes[0]
}

func (x SessionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionStatus.Descriptor instead.
func (SessionStatus) EnumDescriptor() ([]byte, []int) {
	return file_mpc_v1_proto_rawDescGZIP(), []int{0}
}

type SessionConfig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OrgId             string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Chain             string                 `protobuf:"bytes,2,opt,name=chain,proto3" json:"chain,omitempty"`
	Algorithm         string                 `protobuf:"bytes,3,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	Curve             string                 `protobuf:"bytes,4,opt,name=curve,proto3" json:"curve,omitempty"`
	Threshold         uint32                 `protobuf:"varint,5,opt,name=threshold,proto3" json:"threshold,omitempty"`
	Parties           []string               `protobuf:"bytes,6,rep,name=parties,proto3" json:"parties,omitempty"`
	SessionTtlSeconds uint32                 `protobuf:"varint,7,opt,name=session_ttl_seconds,json=sessionTtlSeconds,proto3" json:"session_ttl_seconds,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SessionConfig) Reset() {
	*x = SessionConfig{}
	mi := &file_mpc_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionConfig) ProtoMessage() {}

func (x *SessionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionConfig.ProtoReflect.Descriptor instead.
func (*SessionConfig) Descriptor() ([]byte, []int) {
	return file_mpc_v1_proto_rawDescGZIP(), []int{0}
}

func (x *SessionConfig) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *SessionConfig) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *SessionConfig) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *SessionConfig) GetCurve() string {
	if x != nil {
		return x.Curve
	}
	return ""
}

func (x *SessionConfig) GetThreshold() uint32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *SessionConfig) GetParties() []string {
	if x != nil {
		return x.Parties
	}
	return nil
}

func (x *SessionConfig) GetSessionTtlSeconds() uint32 {
	if x != nil {
		return x.SessionTtlSeconds
	}
	return 0
}

type StartDkgRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	CorrelationId string                 `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Config        *SessionConfig         `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartDkgRequest) Reset() {
	*x = StartDkgRequest{}
	mi := &file_mpc_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartDkgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartDkgRequest) ProtoMessage() {}

func (x *StartDkgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartDkgRequest.ProtoReflect.Descriptor instead.
func (*StartDkgRequest) Descriptor() ([]byte, []int) {
	return file_mpc_v1_proto_rawDescGZIP(), []int{1}
}

func (x *StartDkgRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *StartDkgRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *StartDkgRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StartDkgRequest) GetConfig() *SessionConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type StartDkgResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status        SessionStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=mpc.v1.SessionStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartDkgResponse) Reset() {
	*x = StartDkgResponse{}
	mi := &file_mpc_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartDkgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartDkgResponse) ProtoMessage() {}

func (x *StartDkgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartDkgResponse.ProtoReflect.Descriptor instead.
func (*StartDkgResponse) Descriptor() ([]byte, []int) {
	return file_mpc_v1_proto_rawDescGZIP(), []int{2}
}

func (x *StartDkgResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StartDkgResponse) GetStatus() SessionStatus {
	if x != nil {
		return x.Status
	}
	return SessionStatus_SESSION_STATUS_UNSPECIFIED
}

type StartSignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	CorrelationId string                 `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	KeyId         string                 `protobuf:"bytes,4,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Digest        []byte                 `protobuf:"bytes,5,opt,name=digest,proto3" json:"digest,omitempty"`
	Config        *SessionConfig         `protobuf:"bytes,6,opt,name=config,proto3" json:"config,omitempty"`
	Participants  []string               `protobuf:"bytes,7,rep,name=participants,proto3" json:"participants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSignRequest) Reset() {
	*x = StartSignRequest{}
	mi := &file_mpc_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSignRequest) ProtoMessage() {}

func (x *StartSignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSignRequest.ProtoReflect.Descriptor instead.
func (*StartSignRequest) Descriptor() ([]byte, []int) {
	return file_mpc_v1_proto_rawDescGZIP(), []int{3}
}

func (x *StartSignRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *StartSignRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *StartSignRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StartSignRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *StartSignRequest) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *StartSignRequest) GetConfig() *SessionConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *StartSignRequest) GetParticipants() []string {
	if x != nil {
		return x.Participants
	}
	return nil
}

type StartSignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status        SessionStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=mpc.v1.SessionStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSignResponse) Reset() {
	*x = StartSignResponse{}
	mi := &file_mpc_v1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSignResponse) ProtoMessage() {}

func (x *StartSignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSignResponse.ProtoReflect.Descriptor instead.
func (*StartSignResponse) Descriptor() ([]byte, []int) {
	return file_mpc_v1_proto_rawDescGZIP(), []int{4}
}

func (x *StartSignResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StartSignResponse) GetStatus() SessionStatus {
	if x != nil {
		return x.Status
	}
	return SessionStatus_SESSION_STATUS_UNSPECIFIED
}

type Frame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	OrgId         string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	MessageId     string                 `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Seq           uint64                 `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"`
	Round         uint32                 `protobuf:"varint,5,opt,name=round,proto3" json:"round,omitempty"`
	FromParty     string                 `protobuf:"bytes,6,opt,name=from_party,json=fromParty,proto3" json:"from_party,omitempty"`
	ToParty       string                 `protobuf:"bytes,7,opt,name=to_party,json=toParty,proto3" json:"to_party,omitempty"`
	Payload       []byte                 `protobuf:"bytes,8,opt,name=payload,proto3" json:"payload,omitempty"`
	CorrelationId string                 `protobuf:"bytes,9,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	SentAt        *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	Stage         string                 `protobuf:"bytes,11,opt,name=stage,proto3" json:"stage,omitempty"`
	RoundHint     uint32                 `protobuf:"varint,12,opt,name=round_hint,json=roundHint,proto3" json:"round_hint,omitempty"`
	Broadcast     bool                   `protobuf:"varint,13,opt,name=broadcast,proto3" json:"broadcast,omitempty"`
	Protocol      string                 `protobuf:"bytes,14,opt,name=protocol,proto3" json:"protocol,omitempty"`
	MessageType   string                 `protobuf:"bytes,15,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	PayloadHash   string                 `protobuf:"bytes,16,opt,name=payload_hash,json=payloadHash,proto3" json:"payload_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_mpc_v1_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_mpc_v1_proto_rawDescGZIP(), []int{5}
}

func (x *Frame) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Frame) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *Frame) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Frame) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Frame) GetRound() uint32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *Frame) GetFromParty() string {
	if x != nil {
		return x.FromParty
	}
	return ""
}

func (x *Frame) GetToParty() string {
	if x != nil {
		return x.ToParty
	}
	return ""
}

func (x *Frame) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Frame) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *Frame) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

func (x *Frame) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *Frame) GetRoundHint() uint32 {
	if x != nil {
		return x.RoundHint
	}
	return 0
}

func (x *Frame) GetBroadcast() bool {
	if x != nil {
		return x.Broadcast
	}
	return false
}

func (x *Frame) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Frame) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *Frame) GetPayloadHash() string {
	if x != nil {
		return x.PayloadHash
	}
	return ""
}

var File_mpc_v1_proto protoreflect.FileDescriptor

const file_mpc_v1_proto_rawDesc = "" +
	"\n" +
	"\fmpc.v1.proto\x12\x06mpc.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd8\x01\n" +
	"\rSessionConfig\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x14\n" +
	"\x05chain\x18\x02 \x01(\tR\x05chain\x12\x1c\n" +
	"\talgorithm\x18\x03 \x01(\tR\talgorithm\x12\x14\n" +
	"\x05curve\x18\x04 \x01(\tR\x05curve\x12\x1c\n" +
	"\tthreshold\x18\x05 \x01(\rR\tthreshold\x12\x18\n" +
	"\aparties\x18\x06 \x03(\tR\aparties\x12.\n" +
	"\x13session_ttl_seconds\x18\a \x01(\rR\x11sessionTtlSeconds\"\xa5\x01\n" +
	"\x0fStartDkgRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12%\n" +
	"\x0ecorrelation_id\x18\x02 \x01(\tR\rcorrelationId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12-\n" +
	"\x06config\x18\x04 \x01(\v2\x15.mpc.v1.SessionConfigR\x06config\"`\n" +
	"\x10StartDkgResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12-\n" +
	"\x06status\x18\x02 \x01(\x0e2\x15.mpc.v1.SessionStatusR\x06status\"\xf9\x01\n" +
	"\x10StartSignRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12%\n" +
	"\x0ecorrelation_id\x18\x02 \x01(\tR\rcorrelationId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x15\n" +
	"\x06key_id\x18\x04 \x01(\tR\x05keyId\x12\x16\n" +
	"\x06digest\x18\x05 \x01(\fR\x06digest\x12-\n" +
	"\x06config\x18\x06 \x01(\v2\x15.mpc.v1.SessionConfigR\x06config\x12\"\n" +
	"\fparticipants\x18\a \x03(\tR\fparticipants\"a\n" +
	"\x11StartSignResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12-\n" +
	"\x06status\x18\x02 \x01(\x0e2\x15.mpc.v1.SessionStatusR\x06status\"\xe9\x03\n" +
	"\x05Frame\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tR\tmessageId\x12\x10\n" +
	"\x03seq\x18\x04 \x01(\x04R\x03seq\x12\x14\n" +
	"\x05round\x18\x05 \x01(\rR\x05round\x12\x1d\n" +
	"\n" +
	"from_party\x18\x06 \x01(\tR\tfromParty\x12\x19\n" +
	"\bto_party\x18\a \x01(\tR\atoParty\x12\x18\n" +
	"\apayload\x18\b \x01(\fR\apayload\x12%\n" +
	"\x0ecorrelation_id\x18\t \x01(\tR\rcorrelationId\x123\n" +
	"\asent_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\x12\x14\n" +
	"\x05stage\x18\v \x01(\tR\x05stage\x12\x1d\n" +
	"\n" +
	"round_hint\x18\f \x01(\rR\troundHint\x12\x1c\n" +
	"\tbroadcast\x18\r \x01(\bR\tbroadcast\x12\x1a\n" +
	"\bprotocol\x18\x0e \x01(\tR\bprotocol\x12!\n" +
	"\fmessage_type\x18\x0f \x01(\tR\vmessageType\x12!\n" +
	"\fpayload_hash\x18\x10 \x01(\tR\vpayloadHash*\xa2\x01\n" +
	"\rSessionStatus\x12\x1e\n" +
	"\x1aSESSION_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16SESSION_STATUS_RUNNING\x10\x01\x12\x1c\n" +
	"\x18SESSION_STATUS_COMPLETED\x10\x02\x12\x19\n" +
	"\x15SESSION_STATUS_FAILED\x10\x03\x12\x1c\n" +
	"\x18SESSION_STATUS_TIMED_OUT\x10\x042\x91\x01\n" +
	"\x0eControlService\x12=\n" +
	"\bStartDkg\x12\x17.mpc.v1.StartDkgRequest\x1a\x18.mpc.v1.StartDkgResponse\x12@\n" +
	"\tStartSign\x12\x18.mpc.v1.StartSignRequest\x1a\x19.mpc.v1.StartSignResponse2;\n" +
	"\fRelayService\x12+\n" +
	"\aConnect\x12\r.mpc.v1.Frame\x1a\r.mpc.v1.Frame(\x010\x01BHZFgithub.com/BroLabel/brosettlement-mpc-co-signer/api/proto/mpc/v1;mpcv1b\x06proto3"

var (
	file_mpc_v1_proto_rawDescOnce sync.Once
	file_mpc_v1_proto_rawDescData []byte
)

func file_mpc_v1_proto_rawDescGZIP() []byte {
	file_mpc_v1_proto_rawDescOnce.Do(func() {
		file_mpc_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mpc_v1_proto_rawDesc), len(file_mpc_v1_proto_rawDesc)))
	})
	return file_mpc_v1_proto_rawDescData
}

var file_mpc_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mpc_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_mpc_v1_proto_goTypes = []any{
	(SessionStatus)(0),            // 0: mpc.v1.SessionStatus
	(*SessionConfig)(nil),         // 1: mpc.v1.SessionConfig
	(*StartDkgRequest)(nil),       // 2: mpc.v1.StartDkgRequest
	(*StartDkgResponse)(nil),      // 3: mpc.v1.StartDkgResponse
	(*StartSignRequest)(nil),      // 4: mpc.v1.StartSignRequest
	(*StartSignResponse)(nil),     // 5: mpc.v1.StartSignResponse
	(*Frame)(nil),                 // 6: mpc.v1.Frame
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_mpc_v1_proto_depIdxs = []int32{
	1, // 0: mpc.v1.StartDkgRequest.config:type_name -> mpc.v1.SessionConfig
	0, // 1: mpc.v1.StartDkgResponse.status:type_name -> mpc.v1.SessionStatus
	1, // 2: mpc.v1.StartSignRequest.config:type_name -> mpc.v1.SessionConfig
	0, // 3: mpc.v1.StartSignResponse.status:type_name -> mpc.v1.SessionStatus
	7, // 4: mpc.v1.Frame.sent_at:type_name -> google.protobuf.Timestamp
	2, // 5: mpc.v1.ControlService.StartDkg:input_type -> mpc.v1.StartDkgRequest
	4, // 6: mpc.v1.ControlService.StartSign:input_type -> mpc.v1.StartSignRequest
	6, // 7: mpc.v1.RelayService.Connect:input_type -> mpc.v1.Frame
	3, // 8: mpc.v1.ControlService.StartDkg:output_type -> mpc.v1.StartDkgResponse
	5, // 9: mpc.v1.ControlService.StartSign:output_type -> mpc.v1.StartSignResponse
	6, // 10: mpc.v1.RelayService.Connect:output_type -> mpc.v1.Frame
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_mpc_v1_proto_init() }
func file_mpc_v1_proto_init() {
	if File_mpc_v1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mpc_v1_proto_rawDesc), len(file_mpc_v1_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_mpc_v1_proto_goTypes,
		DependencyIndexes: file_mpc_v1_proto_depIdxs,
		EnumInfos:         file_mpc_v1_proto_enumTypes,
		MessageInfos:      file_mpc_v1_proto_msgTypes,
	}.Build()
	File_mpc_v1_proto = out.File
	file_mpc_v1_proto_goTypes = nil
	file_mpc_v1_proto_depIdxs = nil
}
